package rdpserver

func (s *Server) metrics() serverMetrics {
	return serverMetrics{
		framesSent:             &s.framesSent,
		bitmapBytes:            &s.bitmapBytes,
		bitmapRLEFrames:        &s.bitmapRLEFrames,
		bitmapRLEBytes:         &s.bitmapRLEBytes,
		bitmapRLESavedBytes:    &s.bitmapRLESavedBytes,
		nsCodecFrames:          &s.nsCodecFrames,
		nsCodecBytes:           &s.nsCodecBytes,
		nsCodecRawBytes:        &s.nsCodecRawBytes,
		nsCodecSavedBytes:      &s.nsCodecSavedBytes,
		jpegCodecFrames:        &s.jpegCodecFrames,
		jpegCodecBytes:         &s.jpegCodecBytes,
		jpegCodecRawBytes:      &s.jpegCodecRawBytes,
		jpegCodecSavedBytes:    &s.jpegCodecSavedBytes,
		pngCodecFrames:         &s.pngCodecFrames,
		pngCodecBytes:          &s.pngCodecBytes,
		pngCodecRawBytes:       &s.pngCodecRawBytes,
		pngCodecSavedBytes:     &s.pngCodecSavedBytes,
		rfxCodecFrames:         &s.rfxCodecFrames,
		rfxCodecBytes:          &s.rfxCodecBytes,
		rfxCodecRawBytes:       &s.rfxCodecRawBytes,
		rfxCodecSavedBytes:     &s.rfxCodecSavedBytes,
		bitmapCodecStreamStops: &s.bitmapCodecStreamStops,
		rdpgfxFrames:           &s.rdpgfxFrames,
		rdpgfxBytes:            &s.rdpgfxBytes,
		rdpgfxStreamStops:      &s.rdpgfxStreamStops,
		rdpgfxPath:             &s.rdpgfxPath,
		h264Frames:             &s.h264Frames,
		h264Bytes:              &s.h264Bytes,
		dvcFragments:           &s.dvcFragments,
		h264Status:             &s.h264Status,
		rfxEncoder:             s.rfxEncoder,
		clearCodecEncoder:      s.clearCodecEncoder,
		progressiveEncoder:     s.progressiveEncoder,
		avc444Encoder:          s.avc444Encoder,
		avc444v2Encoder:        s.avc444v2Encoder,
	}
}
